### PR TITLE
initial content

### PR DESCRIPTION
**Pull request by thomas-fossati**
Some very rough content (feel free to suggest edits!)

### CODE REVIEW

**Review by gkostal — APPROVED** [review]
LGTM, thanks!

**Review by shnwc — APPROVED** [review]
Looks good, thanks!

**Comment by dcmiddle** [comment]
Looks good. Maybe drop a link to https://confidentialcomputing.io/ somewhere in the top?
This readme file might need to be in the /profile directory to work right..
https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-public-organization-profile-readme

**Comment by thomas-fossati** [comment]
> Looks good. Maybe drop a link to https://confidentialcomputing.io/ somewhere in the top?

👍 

> This readme file might need to be in the /profile directory to work right..
> https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-public-organization-profile-readme

You are right, thanks!

**Review by dcmiddle — APPROVED** [review]

**Pull request merged**
